In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('twitter_training.csv')

In [3]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [4]:
data.tail()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [5]:
data.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='str')

In [6]:
data=data.sample(15000,random_state=42)

## Data Exploration

In [7]:
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

In [8]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [9]:
data.duplicated().sum()

127

## Data Cleaning

In [10]:
data=data.dropna()

In [11]:
data.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [12]:
data=data.drop_duplicates()

In [13]:
data.shape

(14746, 4)

In [14]:
data.duplicated().sum()

0

In [15]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [16]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [17]:
data.columns

Index(['Positive', 'im getting on borderlands and i will murder you all ,'], dtype='str')

In [18]:
data.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace=True)

In [19]:
data.head()

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [20]:
data['Sentiment'].value_counts()

Sentiment
Negative      4418
Positive      4201
Neutral       3508
Irrelevant    2619
Name: count, dtype: int64

In [21]:
data=data[(data['Sentiment']=='Positive')|(data['Sentiment']=='Negative')|(data['Sentiment']=='Neutral')]

In [22]:
data['Sentiment'].value_counts()

Sentiment
Negative    4418
Positive    4201
Neutral     3508
Name: count, dtype: int64

## Feature Eng..

In [23]:
from sklearn.preprocessing import LabelEncoder

/Users/aseem/Desktop/Tutedude_GENAI/Python/venv/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:14: UserWarning: A NumPy version >=2.0.0 and <2.8.0 is required for this version of SciPy (detected version 1.26.4)
  from scipy.sparse import csr_array, issparse
/Users/aseem/Desktop/Tutedude_GENAI/Python/venv/lib/python3.12/site-packages/scipy/sparse/_sputils.py:17: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  np.uintc, np.long, np.ulong, np.longlong, np.ulonglong,

AttributeError: module 'numpy' has no attribute 'long'

In [ ]:
le=LabelEncoder()

In [ ]:
import pickle

In [ ]:
data['Sentiment']=le.fit_transform(data['Sentiment'])

In [ ]:
data.head()

       Sentiment                                             Tweets
21704          2         Yo this looks LIT! Team:GO/Overwatch combo
47008          0  Pay attention executive administrators. While ...
454            2                                                one
58076          0       @Rainbow6Game Server are Available in Xbox 🥺
40659          2  so Awesome siege attempt... strangest bleeding...

In [ ]:
from tensorflow.keras.preprocessing import Tokenizer

2026-10-27 21:03:17.867512: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.